title = "PEDS configuration file"

[model]
dimension = 2          # dimension of problem
filename = "model_2d.pth"

[discretisation]
n = 32             # number of grid cells
scaling_factor = 8 # ratio between fine and coarse grid cells

[qoi]
sample_points = [[0.790,0.356],[0.743,0.873],[0.456,0.914],[0.293,0.291],[0.123,0.434],[0.222,0.851],[0.865,0.638],[0.207,0.096],[0.940,0.129],[0.529,0.422]]

[data]
Lambda = 0.02          # correlation length
a_power = 2            # power in log-normal distribution
n_samples_train = 2048 # number of training samples
n_samples_valid = 32   # number of validation samples
n_samples_test = 32    # number of test samples
filename = "data_2d.npy"  # name of file with data

[train]
batch_size = 64     # batch size
n_epoch = 512       # number of epochs
lr_initial = 1.0e-2 # initial learning rate
lr_final = 1.0e-3   # final learning rate
