name: Automated tests

on:
  push:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  AutomatedTesting:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"    
    - name: Install PETSc/petsc4py, prerequisites and run tests
      env:
          PYTEST_ADDOPTS: "--color=yes --disable-warnings"
      run: |
        conda init
        conda install -c conda-forge petsc
        conda install -c conda-forge petsc4py         
        python -m pip install pytest
        python -m pip install .
        python -m pytest -v
    